### PR TITLE
Win azure

### PR DESCRIPTION
**Pull request by raholler**
Pull request is only for comparison to master branch, somehow the pre-commits fail on this branch, don't know why.

### CODE REVIEW

**Comment by raholler** [comment]
@hmgaudecker so windows still fails after removing the latex stuff.. do not really understand wafs output though...

**Comment by hmgaudecker** [comment]
All tests seem to fail because `dot` is not found: 
```
ngraphviz.backend.ExecutableNotFound: failed to execute [\'dot\', \'-Tpng\', \'-O\', \'C:\\\\Users\\\\VssAdministrator\\\\AppData\\\\Local\\\\Temp\\\\pytest-of-VssAdministrator\\\\pytest-2\\\\test_waf_build_r0\\\\cookies\\\\bake00\\\\research_project\\\\bld\\\\out\\\\figures\\\\dag\'], make sure the Graphviz executables are on your systems\' PATH\r\n'
```
Does that setup work fine on your machine? I does look like graphviz installed okay, weird...

**Comment by raholler** [comment]
It indeeds also fails on my machine. This is rather new though... A month or so ago, it was still working. 
Maybe related to https://github.com/conda-forge/graphviz-feedstock/issues/34.

**Comment by raholler** [comment]
Indeed an issue of the graphviz version, fixing it at 0.8 resolves this issue.

**Comment by raholler** [comment]
But we seem to have a new problem. The latex installation on mac seems to take too long, so azure cancels it. Should I remove the latex stuff for mac too.

**Comment by hmgaudecker** [comment]
Fair enough. Should be trivial to do now, right?

**Pull request merged**
