### PR TITLE
Prepare v0.2

### PR DESCRIPTION
**Pull request by raholler**
Left to dos:
- Add some more words to the README (i thought that might be better if you do that)
- Add release notes (did I understand it correctly that you will do that)

I corrected a little language in the docs. Rearranged the getting started. Added a developers section. Adapted the R prerequisetes. Setup a new Readme with badges. Changed the pytests so that R stuff is no longer xfail since it should now run on every machine within our conda environment.

### CODE REVIEW

**Comment by hmgaudecker** [comment]
Re release notes: if possible, please add a document with headings in the root folder and link it to the docs so it is a section there. Thanks!

**Comment by raholler** [comment]
> 
> 
> Re release notes: if possible, please add a document with headings in the root folder and link it to the docs so it is a section there. Thanks!

Done.

**Comment by raholler** [comment]
Are you waiting for anything from me?

**Comment by hmgaudecker** [comment]
> Are you waiting for anything from me?

No, I just had not gotten around to doing anything. Looks great. I updated a couple of things and will need to write more. Feel free to add to the two sections of the README and additional points to the release notes, the next few days look pretty tight. Looking for a release towards the weekend or early next week.

Just curious: Are the R example things in the prerequisites section up to date?

**Comment by raholler** [comment]
> Just curious: Are the R example things in the prerequisites section up to date?

Forgot to remove IVpack from that list. Everything else is still required.

**Pull request merged**
