### PR TITLE
Newdocs

### PR DESCRIPTION
**Pull request by raholler**

### CODE REVIEW

**Comment by raholler** [comment]
tackles #52 and #28

**Comment by raholler** [comment]
Pytests fail because of something stupid with graphviz. But I am done for today.

**Comment by raholler** [comment]
Do we maybe need to add Latex to path? Or use a different tex distribution?

**Comment by hmgaudecker** [comment]
We may want to add a prominent sentence or some in the introduction of how to work with the example. I.e., install one and then read intro side-by-side. 

In general, I think it does not fully become obvious to the reader at the moment which part of the docs suits which purpose. But we may want to postpone that until November or so.

**Comment by hmgaudecker** [comment]
> Do we maybe need to add Latex to path? Or use a different tex distribution?

For MacOS, maybe the former. I have not used homebrew in almost a decade...

For Linux, I think the root cause is the lack of interaction. Let's see whether 028c1f9 helps.

**Comment by hmgaudecker** [comment]
Nope, that did not do the trick yet. But I found some stuff going into that direction, might be worth investigating further. I just have to stop for today.

**Comment by hmgaudecker** [comment]
Progress based on 798e748... :-) 
```
Checking for program 'pdflatex'          : /usr/bin/pdflatex 
```
But ... 
```
! LaTeX Error: File `a4wide.sty' not found.
```

**Comment by hmgaudecker** [comment]
Tests pass in fc4cdd1 for Linux :-)

Not sure about this guy; do we need to compile the docs on Azure? I would be fine leaving that out unless it mimics the setup in readthedocs exactly and would alert us early that things will fail there. 

```
2019-08-05T12:43:32.5371865Z [5/5] Running  [Python] src/python/project_hierarchies.py analysis
2019-08-05T12:43:33.1316340Z Traceback (most recent call last):
2019-08-05T12:43:33.1317068Z   File "/home/vsts/work/1/s/docs/src/python/organisation_model_steps.py", line 184, in <module>
2019-08-05T12:43:33.1318779Z     y_items=model_shapes["None"],
2019-08-05T12:43:33.1319110Z   File "/home/vsts/work/1/s/docs/src/python/organisation_model_steps.py", line 178, in create_fig
2019-08-05T12:43:33.1319428Z     plt.savefig("{}.{}".format(out_file, EXPORT_TYPE))
2019-08-05T12:43:33.1320989Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/pyplot.py", line 716, in savefig
2019-08-05T12:43:33.1321548Z     res = fig.savefig(*args, **kwargs)
2019-08-05T12:43:33.1322210Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
2019-08-05T12:43:33.1322625Z     self.canvas.print_figure(fname, **kwargs)
2019-08-05T12:43:33.1323290Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
2019-08-05T12:43:33.1325149Z     **kwargs)
2019-08-05T12:43:33.1325899Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 926, in print_png
2019-08-05T12:43:33.1326236Z     self._print_png_to_fh(file, *args, **kwargs)
2019-08-05T12:43:33.1326907Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 909, in _print_png_to_fh
2019-08-05T12:43:33.1327221Z     self.print_pdf(fname_pdf, *args, **kwargs)
2019-08-05T12:43:33.1327844Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 898, in print_pdf
2019-08-05T12:43:33.1328200Z     self._print_pdf_to_fh(file, *args, **kwargs)
2019-08-05T12:43:33.1328745Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 861, in _print_pdf_to_fh
2019-08-05T12:43:33.1329126Z     self.print_pgf(fname_pgf, *args, **kwargs)
2019-08-05T12:43:33.1329662Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 848, in print_pgf
2019-08-05T12:43:33.1335149Z     self._print_pgf_to_fh(file, *args, **kwargs)
2019-08-05T12:43:33.1335872Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 828, in _print_pgf_to_fh
2019-08-05T12:43:33.1336274Z     RendererPgf(self.figure, fh),
2019-08-05T12:43:33.1336871Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 397, in __init__
2019-08-05T12:43:33.1337215Z     self.latexManager = LatexManager._get_cached_or_new()
2019-08-05T12:43:33.1337826Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 233, in _get_cached_or_new
2019-08-05T12:43:33.1338155Z     return cls._get_cached_or_new_impl(cls._build_latex_header())
2019-08-05T12:43:33.1338773Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 238, in _get_cached_or_new_impl
2019-08-05T12:43:33.1339127Z     return cls()
2019-08-05T12:43:33.1339663Z   File "/usr/share/miniconda/envs/econ-project-templates/lib/python3.7/site-packages/matplotlib/backends/backend_pgf.py", line 294, in __init__
2019-08-05T12:43:33.1340626Z     "or error in preamble:
%s" % stdout)
2019-08-05T12:43:33.1341015Z matplotlib.backends.backend_pgf.LatexError: LaTeX returned an error, probably missing font or error in preamble:
2019-08-05T12:43:33.1343232Z b"This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
```

**Pull request merged**
